In [1]:
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2" # no errors in pycharm

import tensorflow as tf

In [2]:
x = tf.constant(2)
print(x)

tf.Tensor(2, shape=(), dtype=int32)


In [3]:
x_zero = tf.zeros((2,2))
print(x_zero)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [7]:
y = tf.ones((4,5))
y

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [12]:
y = tf.range(9)
print(y)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [13]:
y= tf.range(start=20, limit=100, delta= 5)
print(y )

tf.Tensor([20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95], shape=(16,), dtype=int32)


In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([9,7,8])

In [18]:
z = x + y
print(z)

tf.Tensor([22 27 32 37 42 47 52 57 62 67 72 77 82 87 92 97], shape=(16,), dtype=int32)


In [22]:
z

<tf.Tensor: shape=(16,), dtype=int32, numpy=
array([22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87, 92, 97],
      dtype=int32)>

In [ ]:
# Initialization
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
print(x)

x = tf.eye(3)
print(x)

x = tf.ones((4, 3))
print(x)

x = tf.zeros((3, 2, 5))
print(x)

x = tf.random.uniform((2, 2), minval=0, maxval=1)
print(x)

x = tf.random.normal((3, 3), mean=0, stddev=1)
print(tf.cast(x, dtype=tf.float64))
# tf.float (16,32,64), tf.int (8, 16, 32, 64), tf.bool

x = tf.range(9)
x = tf.range(start=0, limit=10, delta=2)
print(x)



In [ ]:

# Math
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z = tf.add(x, y)
z = x + y

z = tf.subtract(x, y)
z = x - y

z = tf.divide(x, y)
z = x / y

z = tf.multiply(x, y)
z = x * y

z = tf.tensordot(x, y, axes=1)

z = x ** 5

x = tf.random.normal((2, 3))
y = tf.random.normal((3, 2))
z = tf.matmul(x, y)
z = x @ y

x = tf.random.normal((2, 2))



In [ ]:
# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

indices = tf.constant([0, 3])
x_indices = tf.gather(x, indices)

x = tf.constant([[1, 2], [3, 4], [5, 6]])

print(x[0, :])
print(x[0:2, :])

In [ ]:

# Reshaping
x = tf.range(9)

x = tf.reshape(x, (3, 3))

x = tf.transpose(x, perm=[1, 0])